### ISSUE TITLE
Persistence is not working on the HOST only on other clients

### ISSUE THREAD

**Issue by sousou63** [sousou63/DarkRP-old#126]

**Comment by EuroBlue** [comment]
Ok here is the thing when hosts leaves ot deleats the player on its own without remove player you can see it in the logs
2024/08/21 01:16:12.8162    [GameMenu] Removing player: 5f82bb60-8fef-4fbc-af12-7eae8734b230 hepe_fuil
2024/08/21 01:16:12.8162    [GameMenu] Player not found in the list: 5f82bb60-8fef-4fbc-af12-7eae8734b230
![2024-08-21-013036_hyprshot](https://github.com/user-attachments/assets/345835c2-51eb-40e7-a89d-caf1bc106da6)
So what we need to do is to find out why the Player is being deleted on it's own and then fix it and were finished

**Comment by EuroBlue** [comment]
![image](https://github.com/user-attachments/assets/6fdef60d-e23e-4a2a-b56a-c19c4e28c7dd)

**Comment by EuroBlue** [comment]
![image](https://github.com/user-attachments/assets/020da558-398f-48d6-848a-1b4da9af7863)

**Comment by EuroBlue** [comment]
![image](https://github.com/user-attachments/assets/dcfe36cd-18a6-4c09-9e8e-42da7923b4c6)

**Comment by EuroBlue** [comment]
Possible fix
![image](https://github.com/user-attachments/assets/ce319aa3-047a-4694-99d5-9bdd59de4896)

**Comment by sousou63** [comment]
Almost fixed, but now persistence work so no need to focus on this issue anymore.

**Comment by sousou63** [comment]
I think I can close it.
