### ISSUE TITLE
Sandbank For Storing Data

### ISSUE THREAD

**Issue by anthonysharpy** [sousou63/DarkRP-old#186]
Hi! Hope you are well!

I have to apologise in advance because this is basically just going to be me shamelessly plugging my own library...

So I noticed that it looks like the plan currently is to store game data in a traditional database: https://github.com/sousou63/DarkRP/blob/main/code/Persistence/Database.cs

I was wondering if you had considered using my database library? (https://github.com/anthonysharpy/sandbank)

I think the advantages of this would be:

- It's faster
- It's a lot simpler for people to implement (currently for the traditional database approach to work you'd need to host an API and a database, which is probably a headache for most people) 
- It's cheaper (no need to pay for database/API hosting)
- You can start implementing it now (rather than waiting for a feature that Facepunch might never add)
- It would simplify your code

If you think it sounds like a good idea then I can even make a PR implementing this for you.

If you have any questions please ask 😄

**Comment by ghost** [comment]
@anthonysharpy Please read the reply in the new repository.
