### ISSUE TITLE
The more money you have, the bigger the Bar becomes

### ISSUE THREAD

**Issue by Mangrogred** [sousou63/DarkRP-old#46]
![изображение](https://github.com/user-attachments/assets/bc2dfb63-26cd-4fe8-9e4c-851348a410f0)

![изображение](https://github.com/user-attachments/assets/1ef15540-ab7f-41cf-94fd-f7de1af42370)

**Comment by SebbeJohansson** [comment]
This seems to be a duplicate of #36. correct?

**Comment by Mangrogred** [comment]
Fixed (by myself)
